@url=http://localhost:4004

###
# Call the external API
# should return 100 items
GET {{url}}/odata/v4/external-api/ExternalApi

###
# get businesspartners
GET {{url}}/CatalogService/businesspartner

###
# number of business partners
GET {{url}}/CatalogService/businesspartner/$count